import type { Metadata } from "next";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

import { Lora, Montserrat, Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body className={montserrat.className}>
				<div className="fixed top-0 w-full z-50">
					<Navbar />
				</div>

				<div className="min-h-screen">{children}</div>

				<Footer />
			</body>
		</html>
	);
}
